'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.1
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TEC_SARL.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _04_go_fish_avi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("04-go fish.avi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3D_Neutre_Lemon__1280x1024_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3D_Neutre_Lemon (1280x1024)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property affect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("affect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Application_de_commande_online() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Application-de-commande-online", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property apply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property client() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("client", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property commande() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("commande", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connexion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connexion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contrat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contrat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contrat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contrat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property demarrage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarrage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property demarrage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarrage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit (4)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property facture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property facturer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facturer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property facturere() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facturere", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fond21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fond21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fond211() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fond211", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondObjImmat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondObjImmat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondObjImmat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondObjImmat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondObjImmat2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondObjImmat2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gestion_des_Fournitures() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gestion des Fournitures", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon18_wrench_allbkg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon18_wrench_allbkg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image_Acces_Administrataur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image Acces Administrataur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image_acces_Conformité() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image acces Conformité", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image_acces_Conformité1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image acces Conformité1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image_Acces_Service_Achat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image Acces Service Achat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image_de_fond() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image de fond", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_031() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_031", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_0311() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_0311", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_0312() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_0312", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_0313() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_0313", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_0314() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_0314", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property installee_paquet_mis_a_jour_icone_5126_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("installee-paquet-mis-a-jour-icone-5126-128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property livraire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("livraire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property livraison() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("livraison", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property livraison1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("livraison1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property livrere() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("livrere", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property modifier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Page_d_acceuil_Application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Page d'acceuil Application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ph_10049() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ph-10049", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prod() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prod", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property produit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("produit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property produit_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("produit 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RecycleBin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RecycleBin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rocla_oyj_france_preparateur_de_commande_306276() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rocla-oyj-france-preparateur-de-commande-306276", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SAM_2193() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SAM_2193", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SAM_2195() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SAM_2195", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property type_produit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("type produit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vide_poubelle_icone_8363_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vide-poubelle-icone-8363-128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
